### ISSUE TITLE
how to compile tests directory?

### ISSUE THREAD

**Issue by vasco3** [teamwalnut/rewatch#107]
in my rescript.json I have this 
```json
"sources": [
    { "dir": "src/components", "subdirs": false },
    {
      "dir": "tests",
      "subdirs": false,
      "type": "dev"
    }
  ],
```

But i noticed that rewatch doesn't compile my `.test.res` files within the `./tests/` directory. It works with rescript compiler but not with rewatch.

## deps
- `"rescript": "^11.1.0",`
-  `"@rolandpeelen/rewatch": "^1.0.4",`

**Comment by rolandpeelen** [comment]
`.test.res` is not a valid extension name. I think the rescript compiler allows this, but we chose to be more strict here. See this also: https://github.com/glennsl/rescript-jest?tab=readme-ov-file#usage

**Comment by vasco3** [comment]
> `.test.res` is not a valid module name. If you rename to `_test.rest` it should work fine :)
> 
> I think the rescript compiler allows this, but we chose to be more strict here. See this also: https://github.com/glennsl/rescript-jest?tab=readme-ov-file#usage

I tried with `_test.res` but didn't work. Also tried moving them to `__tests__`.
If i remove the `"type": "dev"` they do compile

**Comment by lucas-teks** [comment]
Hi! Same issue here. Removing `"type": "dev"` indeed removed the issue.
