### ISSUE TITLE
Build error for unused attribute: @bs.uncurry

### ISSUE THREAD

**Issue by mununki** [teamwalnut/rewatch#67]
```
 Warning number 101 (configured as error) 
  /Users/woonki/Github/works/gl/sources/farmmorning-app/node_modules/@ryyppy/rescript-promise/src/Promise.res:7:18-28

  5 │ 
  6 │ @bs.new
  7 │ external make: ((@bs.uncurry (. 'a) => unit, (. 'e) => unit) => unit) =>
    │  t<'a> = "Promise"
  8 │ 
  9 │ @bs.val @bs.scope("Promise")

  Unused attribute: bs.uncurry
This means such annotation is not annotated properly. 
for example, some annotations is only meaningful in externals
```
It's not included in my project dependencies directly, but I think it exists in the node_modules folder because one of the npm packages it depends on uses it. I think this build error is preventing me from making progress.

**Comment by zth** [comment]
Change your warnings config to not have `101` as error but just as warning.

**Comment by rolandpeelen** [comment]
I think we don’t support warnings for transitive dependencies. This is something we could look into :)

**Comment by jfrolich** [comment]
Is this still relevant, I think we use the same approach as bsb, if not we should fix the bug

**Comment by vasco3** [comment]
`pnpm run build` works well without error `101` but fails when deploying to Vercel. Any suggestions? I'm using a monorepo.
The lib failing for my is ryyppy rescript-promise

**Comment by rolandpeelen** [comment]
@vasco3 - `Rescript-Promise` does not really look like it's maintained. The `@bs` syntax is not supported anymore afaik.

I see two forward solutions.
1. Upgrade Rescript so you have `Core` library, and use the promise helpers from there.
2. Create a `Promise.res` file locally, and add the code without `@bs.`. [See playground link](https://rescript-lang.org/try?version=v11.1.0&code=C4TwDgpgBMA8DUByAhgPigXigKQM4DoAFAJwHsBbAS1wnzhVQChGIAPAYwjGEtIDscuAKLEyxABR58Q1nzoBKFq2ARifZABsoAVz65kAMwgAVUnhl8AXFDYCM6KRbqYoAIgCklACYQ+PUK7MAAJ8EADuSipqmlDkyADWENbi4kG67NqiIFDi+FAo8pjoupTAADQ5eYgQhfY6fKW1xQ3ATTCwDC6uJBTUEIGMQQBuMUG47KSQ4t1kVDSuimxR6lrEELikGkNJ+chF7Z1YrmsbW-3BNHxeNsqqKzAAFr7J9GgVaXwZWTko+-QARqh5G0AegjsAnnwBmNfF5IncYhDfAAldabbYvDpvKAfL7EbLiX51RD-YF-DqArpIqEXWE3ZYxAyUFYaECYhgVErAfZckFYsFuJkskDQ8aTCDTHpzfqFYaaeHRVYQABWEHYwGstnJAH0BccVWrgKKJlMZr15rKRhoFfdNBprMhRMgQLBXqgweg4I7iM7+Xq7cbxZLZn0FjirTaYnaAEzJcRuiqgsl1OCE5AVEnyf0aDSB01S0OW+VLBFaO0AZjjCYOgMTHXYQL5aYz-wz7CzXQDFxNErN0rDcutJcVUDtABYq-y6yTUNOG9OvI3yc38q38uwM14O0cu4MxfmQxbw8XbiO7QBWSccmuzg7zg6L6cQJcp2ArkltzcZmrZ3PdoN9oWx5Dqeto5gAbFe2KgnOt70I+BzPtOBgvp6b4oC2n75F434ZgY25uLuMJXJGWjauwyDAOwDzstiuKZPiORaq+DDJmhhxuBRVEPAMGgQNyXHUS44hgIeEAVBROb-Mg7DxG0ADejBQFA5GUdRIliRUqjEPsinKcpAD0BlQAAkgIBjaMAmTQNsxC4LwegVGE0ATNoGjXNoNCPNA-z8VEUC2fZ-CWEp+kGQAVFAkkaNJsmSAQTjIHwICmBYZkMho4g1IU4UGcw+lQEZUAGKQOl8KQYRQM5UChBA1zAKQUD-MQzIAOZQKQmQdWEAjmKIpUwOAEChcpfHckMLiUAYgjSLI+DUAAwsg5AaDInDcA5ADyxCbZAfAAGqOpQSXAFloiFHpBU2KII1QAAvjYGheZdBV9WI4i6PoRimOYshncQwK3Xdt3RbF8TiEMijKXdijA3uPbBuaMrAaRUA+pwDpOi6boegcaBdOj5xAA)

No. 2 should have a relatively small diff :)
