### ISSUE TITLE
Resolving dependencies with pnpm

### ISSUE THREAD

**Issue by DZakh** [teamwalnut/rewatch#74]
I have a project using `pnpm` with the following structure:
```
|
- apps/backoffice - uses packages/rescript-sandbox as a dependency
- packages/rescript-sandbox - uses rescript-nodejs as a dependency
```

Which fails with the error:
```
[1/6] 🌴  Building package tree...thread 'main' panicked at 'Errors reading bsconfig: "Could not read bsconfig. /Users/dzakh/code/carla/web-new/apps/backoffice/node_modules/rescript-nodejs/bsconfig.json - No such file or directory (os error 2)"', src/bsconfig.rs:251:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
/Users/dzakh/code/carla/web-new/apps/backoffice/node_modules/.bin/rewatch: line 13: 11690 Abort trap: 6           "$basedir/../../../../node_modules/.pnpm/@rolandpeelen+rewatch@0.0.11/node_modules/@rolandpeelen/rewatch/rewatch" "$@"
```

Since `rescript-nodejs` is a dependency of the `rescript-sandbox` it should be taken from the `packages/rescript-sandbox/node_modules` instead of `apps/backoffice/node_modules`.

**Comment by rolandpeelen** [comment]
Hmm - So, `yarn workspaces` builds a single `node_modules` folder at the root of where you run for the monorepo. It would symlink `rescript-sandbox` in `node_modules`.

Is `node_modules` in the root, alongside `apps` and `packages`?

**Comment by DZakh** [comment]
There's a separate `node_modules` for each app and package. And the dependencies from the `node_modules` symlink into a single `node_modules/.pnpm/` at the root of the workspace to avoid duplicated packages.

**Comment by DZakh** [comment]
https://github.com/DZakh/rescript-struct Uses pnpm, you can try it out there

**Comment by rolandpeelen** [comment]
I'll try and schedule some time to dig into this. Sounds like we need to fallback and try to interject `.pnpm` into the module resolution if we can't find it the first hit. Wdty @jfrolich ?

**Comment by DZakh** [comment]
I think instead of reading dependencies from `.pnpm` it's better to do it from `packages/*/node_modules` and `apps/*/node_modules`
