### ISSUE TITLE
No such file or directory for non-hoisted dependencies

### ISSUE THREAD

**Issue by tsnobip** [teamwalnut/rewatch#82]
I'm using a yarn v4.0 monorepo setup and I can't build using rewatch because non-hoisted dependencies cause the following error:
```
[1/7] 🌴  Building package tree...[1/2] ️🛑   Error building package tree (are node_modules up-to-date?)... 
 More details: No such file or directory (os error 2)%     
```
I have such a file tree:

```
monorepo
├── node_modules
└── packages
     └── packageA
           └──node_modules
               └── @rescript/react
```
dependencies in rescript.json/bsconfig.json that are in the top level node_modules don't cause issues, only the ones inside the package node_modules, like @rescript/react in this case.

Could be related to #74.

**Comment by jfrolich** [comment]
Yes we should address this, shouldn't be hard

**Comment by DZakh** [comment]
Do you have ideas on how to differentiate between monorepos with hoisted and non-hoisted dependencies? Or should we should check both places? It's an IO though, but probably not critical.

**Comment by DZakh** [comment]
Yeah. Makes sense to me. I'll try to finish the pr during the weekend

**Comment by tsnobip** [comment]
Let me know when it's done, I'll test it on my setup

**Comment by DZakh** [comment]
Should be fixed in the PR https://github.com/rolandpeelen/rewatch/pull/91

**Comment by jfrolich** [comment]
This should be fixed 🥳
